### PR TITLE
Added handling for xml escape characters in string values

### PR DESCRIPTION
**Pull request by chrismalek**
I was using this library to convert JSON to XML. I was getting some JSON back from an API that had & in the values which chokes XML processors as & needs to be escaped.

I added some changes to replace some of those strings that needs to be replaced for valid XML.

### CODE REVIEW

**Comment by chrismalek** [comment]
Oops. I think there may be an issue here. Please ignore this PR for now.

**Comment by clbanning** [comment]
With latest update: XMLEscapeChars(true) will force escaping of invalid characters in attribute and element values.

**Comment by clbanning** [comment]
Check latest (just now) update of the repo.  A
      new function XMLEscapeChars(true) will escape invalid characters
      ...  thanks.
    
    On 3/18/16 12:35 PM, Chris Malek wrote:
    
    
      Oops. I think there may be an issue here. Please ignore this PR
        for now. 
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly or view
          it on GitHub

**Comment by chrismalek** [comment]
let me me check that out..ignore my other pull request. I will cancel that.

**Pull request closed without merging**
